module.exports = {
  TABLES: {
    CUSTOMERS: 'Customers',
    WAREHOUSES: 'Warehouses',
    ZONES: 'Zones',
    RACKS: 'Racks',
    STORAGE_LOCATIONS: 'StorageLocations',
    INBOUND_ADVICE: 'InboundAdvice',
    GRN: 'GRN',
    CARGO: 'Cargo',
    CARGO_MOVEMENT_LOG: 'CargoMovementLog',
    SCAN_HISTORY: 'ScanHistory',
    VAL_REQUEST: 'VALRequest',
    VAL_TASK: 'VALTask',
    TASKS: 'Tasks',
    OUTBOUND_REQUEST: 'OutboundRequest',
    PICK_TASK: 'PickTask',
    DISPATCH: 'Dispatch',
    DOCUMENTS: 'Documents',
    ROLE_PERMISSIONS: 'RolePermissions',
    AUDIT_LOG: 'AuditLog',
    APP_USERS: 'AppUsers',
  },
  BUCKETS: {
    DOCUMENTS: 'woms-documents',
    CARGO_PHOTOS: 'woms-cargo-photos',
    QR_LABELS: 'woms-qr-labels',
  },
  SCAN_CONTEXTS: ['receiving', 'storage', 'relocation', 'val', 'dispatch'],
};
